name: qpmpcdoc
channels:
    - conda-forge
dependencies:
    - python = 3.10
    - pip >= 21.3.1
    - sphinx >= 8.0.0
    - pip:
        - sphinx-autodoc-typehints
        - sphinx-material
        - sphinx-mathjax-offline
